command:
  - "streamlit"
  - "run"
  - "app.py"

env:
  - name: MAPPINGS_TABLE
    value: "shm.columnmapping.standardization_mappings"
  - name: APPROVALS_TABLE
    value: "shm.columnmapping.column_approvals"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "148ccb90800933a1"
